services:
  - type: web
    name: django-auctions-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn jabidsBackend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jabidsBackend.settings
      - key: PYTHON_VERSION
        value: 3.11
